name: Build and Deploy Game

on:
  workflow_dispatch:    #запуск вручну
    inputs:
      godot_version:
        description: 'Godot version'
        default: '4.2.1'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: ${{ github.event.inputs.godot_version }}
          use-dotnet: false

      - name: Export Web
        run: |
          mkdir -p builds/web
          godot --headless --export-release "Web" builds/web/index.html

      - name: Export Windows
        run: |
          mkdir -p builds/windows
          godot --headless --export-release "Windows Desktop" builds/windows/game.exe

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-web
          path: builds/web/

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-windows
          path: builds/windows/

      - name: Deploy to itch.io
        uses: Oval-Tutu/publish-to-itch-with-butler@v1
        with:
          api-key: ${{ secrets.BUTLER_API_KEY }}
          itch_user: ${{ secrets.ITCH_USERNAME }}
          itch_game: ${{ secrets.ITCH_GAME_ID }}
          channel: web
          package: ./builds/web/
