name: Deploy to itch.io
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Game version'
        required: true
      description:
        description: 'Update description'
        required: false
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
 
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: game-builds
          path: builds/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
 
      - name: Deploy to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html5
          ITCH_GAME: ${{ secrets.ITCH_GAME_ID }}
          ITCH_USER: ${{ secrets.ITCH_USERNAME }}
          PACKAGE: builds/web